// Code generated by protoc-gen-go.
// source: state.proto
// DO NOT EDIT!

/*
Package go_sheep is a generated protocol buffer package.

It is generated from these files:
	state.proto

It has these top-level messages:
	DelegateCheckRequest
	States
	Target
	Node
	State
*/
package go_sheep

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DelegateCheckRequest struct {
	State  *State `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Target *Node  `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
}

func (m *DelegateCheckRequest) Reset()                    { *m = DelegateCheckRequest{} }
func (m *DelegateCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*DelegateCheckRequest) ProtoMessage()               {}
func (*DelegateCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DelegateCheckRequest) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *DelegateCheckRequest) GetTarget() *Node {
	if m != nil {
		return m.Target
	}
	return nil
}

// States is an array of State objects
type States struct {
	States []*State `protobuf:"bytes,1,rep,name=States,json=states" json:"States,omitempty"`
}

func (m *States) Reset()                    { *m = States{} }
func (m *States) String() string            { return proto.CompactTextString(m) }
func (*States) ProtoMessage()               {}
func (*States) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *States) GetStates() []*State {
	if m != nil {
		return m.States
	}
	return nil
}

// Target is a Node that will be pinged by delegated Nodes
type Target struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Target) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Node contains membership information of a particular host
type Node struct {
	Uuid     string                     `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Address  string                     `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	LastSeen *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=lastSeen" json:"lastSeen,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Node) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetLastSeen() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastSeen
	}
	return nil
}

// State represents an array of Node with their current membership info.
// Each host must have an stored state.
type State struct {
	Nodes []*Node `protobuf:"bytes,4,rep,name=Nodes,json=nodes" json:"Nodes,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *State) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*DelegateCheckRequest)(nil), "go_sheep.DelegateCheckRequest")
	proto.RegisterType((*States)(nil), "go_sheep.States")
	proto.RegisterType((*Target)(nil), "go_sheep.Target")
	proto.RegisterType((*Node)(nil), "go_sheep.Node")
	proto.RegisterType((*State)(nil), "go_sheep.State")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SWIM service

type SWIMClient interface {
	// Ping sends State to a previously randomized address to retrieve its state already merge with ours.
	Ping(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error)
	// DelegateCheck sends State to a delegated node so it can check agains Target node. Returns:
	// - The state of the target AND the delegated node (the node we are connecting to)
	// - The state of the delegated node and an error if it couldn't get state from Target
	// - An error only if something happened
	DelegateCheck(ctx context.Context, in *DelegateCheckRequest, opts ...grpc.CallOption) (*State, error)
	Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*State, error)
}

type sWIMClient struct {
	cc *grpc.ClientConn
}

func NewSWIMClient(cc *grpc.ClientConn) SWIMClient {
	return &sWIMClient{cc}
}

func (c *sWIMClient) Ping(ctx context.Context, in *State, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := grpc.Invoke(ctx, "/go_sheep.SWIM/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sWIMClient) DelegateCheck(ctx context.Context, in *DelegateCheckRequest, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := grpc.Invoke(ctx, "/go_sheep.SWIM/DelegateCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sWIMClient) Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := grpc.Invoke(ctx, "/go_sheep.SWIM/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SWIM service

type SWIMServer interface {
	// Ping sends State to a previously randomized address to retrieve its state already merge with ours.
	Ping(context.Context, *State) (*State, error)
	// DelegateCheck sends State to a delegated node so it can check agains Target node. Returns:
	// - The state of the target AND the delegated node (the node we are connecting to)
	// - The state of the delegated node and an error if it couldn't get state from Target
	// - An error only if something happened
	DelegateCheck(context.Context, *DelegateCheckRequest) (*State, error)
	Join(context.Context, *Node) (*State, error)
}

func RegisterSWIMServer(s *grpc.Server, srv SWIMServer) {
	s.RegisterService(&_SWIM_serviceDesc, srv)
}

func _SWIM_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SWIMServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_sheep.SWIM/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SWIMServer).Ping(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

func _SWIM_DelegateCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegateCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SWIMServer).DelegateCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_sheep.SWIM/DelegateCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SWIMServer).DelegateCheck(ctx, req.(*DelegateCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SWIM_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SWIMServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_sheep.SWIM/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SWIMServer).Join(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _SWIM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go_sheep.SWIM",
	HandlerType: (*SWIMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SWIM_Ping_Handler,
		},
		{
			MethodName: "DelegateCheck",
			Handler:    _SWIM_DelegateCheck_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _SWIM_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "state.proto",
}

func init() { proto.RegisterFile("state.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0xcf, 0x4b, 0xfb, 0x30,
	0x14, 0xff, 0x76, 0x6b, 0xfb, 0x9d, 0x6f, 0xa8, 0xf0, 0xf0, 0x50, 0x76, 0x90, 0x11, 0xfc, 0x0d,
	0xb6, 0x38, 0xc1, 0x8b, 0x37, 0xf5, 0xa2, 0xa0, 0x48, 0x37, 0xf0, 0x28, 0xe9, 0xfa, 0x96, 0x15,
	0xbb, 0xa6, 0x2e, 0xc9, 0xc1, 0x3f, 0xc7, 0xff, 0x54, 0x9a, 0xad, 0xce, 0x95, 0xde, 0x5e, 0xf2,
	0x3e, 0x3f, 0x13, 0xe8, 0x2b, 0xcd, 0x35, 0x85, 0xe5, 0x52, 0x6a, 0x89, 0x3d, 0x21, 0xdf, 0xd5,
	0x9c, 0xa8, 0x1c, 0xdc, 0x8a, 0x4c, 0xcf, 0x4d, 0x12, 0x4e, 0xe5, 0x22, 0x12, 0x32, 0xe7, 0x85,
	0x88, 0x2c, 0x24, 0x31, 0xb3, 0xa8, 0xd4, 0x5f, 0x25, 0xa9, 0x48, 0x67, 0x0b, 0x52, 0x9a, 0x2f,
	0xca, 0xcd, 0xb4, 0x92, 0x61, 0x04, 0x07, 0x0f, 0x94, 0x93, 0xe0, 0x9a, 0xee, 0xe7, 0x34, 0xfd,
	0x88, 0xe9, 0xd3, 0x90, 0xd2, 0x78, 0x0c, 0x9e, 0x75, 0x0b, 0x9c, 0xa1, 0x73, 0xd6, 0x1f, 0xed,
	0x87, 0xb5, 0x5d, 0x38, 0xae, 0xae, 0xe3, 0xd5, 0x16, 0x4f, 0xc0, 0xd7, 0x7c, 0x29, 0x48, 0x07,
	0x1d, 0x8b, 0xdb, 0xdb, 0xe0, 0x5e, 0x64, 0x4a, 0xf1, 0x7a, 0xcb, 0xae, 0xc0, 0xb7, 0x3c, 0x85,
	0xa7, 0xf5, 0x14, 0x38, 0xc3, 0x6e, 0x9b, 0xb2, 0x6f, 0x95, 0x15, 0x63, 0xe0, 0x4f, 0x2c, 0x19,
	0x03, 0xf8, 0xcf, 0xd3, 0x74, 0x49, 0x4a, 0xd9, 0x34, 0x3b, 0x71, 0x7d, 0x64, 0x39, 0xb8, 0x95,
	0x0d, 0x22, 0xb8, 0xc6, 0x64, 0xe9, 0x7a, 0x6d, 0xe7, 0xbf, 0xac, 0xce, 0x16, 0x0b, 0x6f, 0xa0,
	0x97, 0x73, 0xa5, 0xc7, 0x44, 0x45, 0xd0, 0xb5, 0xb1, 0x07, 0xa1, 0x90, 0x52, 0xe4, 0xeb, 0xb7,
	0x4d, 0xcc, 0x2c, 0x9c, 0xd4, 0xef, 0x14, 0xff, 0x62, 0xd9, 0x25, 0x78, 0x36, 0x22, 0x1e, 0x81,
	0x57, 0xd9, 0xaa, 0xc0, 0xb5, 0x15, 0x9a, 0xa5, 0xbd, 0xa2, 0x5a, 0x8e, 0xbe, 0x1d, 0x70, 0xc7,
	0x6f, 0x8f, 0xcf, 0x78, 0x01, 0xee, 0x6b, 0x56, 0x08, 0x6c, 0x56, 0x1d, 0x34, 0x2f, 0xd8, 0x3f,
	0xbc, 0x83, 0xdd, 0xad, 0xff, 0xc0, 0xc3, 0x0d, 0xa6, 0xed, 0xa3, 0xda, 0x34, 0xce, 0xc1, 0x7d,
	0x92, 0x59, 0x81, 0x8d, 0x5c, 0x2d, 0xd0, 0xc4, 0xb7, 0x85, 0xaf, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xa4, 0x73, 0x82, 0x5d, 0x5b, 0x02, 0x00, 0x00,
}
